name : Deploy Nodejs Application
on :
  push:
    branches:
      - main


jobs:
  deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: appleboy/ssh-action@v1.0.3
        with:
          